Repository gui-cs/Terminal.Gui, pull requests merged in 2023-04, with the labels that each got.

#2498 Fixes #2496. Adds simple `Ruler` class for drawing rulers; Thickness and Frame now use
  Terminal.Gui/Core/Frame.cs
  Terminal.Gui/Core/Thickness.cs
  Terminal.Gui/Drawing/Ruler.cs
  UnitTests/Application/ApplicationTests.cs
  UnitTests/Core/ThicknessTests.cs
  UnitTests/Drawing/RulerTests.cs
  UnitTests/TopLevels/ToplevelTests.cs
  UnitTests/Views/FrameViewTests.cs
Labels: v2

#2507 Fixed global.json to use 7.0
  global.json
Labels: v1

#2576 Fixes #2575 - TableView to use interface instead of System.Data.DataTable
  Terminal.Gui/Views/FileDialog.cs
  Terminal.Gui/Views/TableView/CellActivatedEventArgs.cs
  Terminal.Gui/Views/TableView/DataTableSource.cs
  Terminal.Gui/Views/TableView/EnumerableTableSource.cs
  Terminal.Gui/Views/TableView/ITableSource.cs
  Terminal.Gui/Views/TableView/SelectedCellChangedEventArgs.cs
  Terminal.Gui/Views/TableView/TableView.cs
  UICatalog/Scenarios/CsvEditor.cs
  UICatalog/Scenarios/MultiColouredTable.cs
  UICatalog/Scenarios/ProcessTable.cs
  UICatalog/Scenarios/TableEditor.cs
  UICatalog/UICatalog.cs
  UnitTests/Views/TableViewTests.cs
  docfx/articles/tableview.md
Labels: breaking-change, v2
