Repository gui-cs/Terminal.Gui, pull requests merged in 2023-07, with the labels that each got.

#2708 Fix tileview borders and enable tests
  Terminal.Gui/Views/TileView.cs
  UnitTests/Views/TileViewTests.cs
Labels: v2

#2721 Added info about PoshDotnetDumpAnalyzeViewer
  README.md
Labels: docs, v1

#2691 Add table example check to prevent crashes
  UICatalog/Scenarios/TableEditor.cs
Labels: v1

#2718 Fixes #2717. Label not display fully when resizing terminal.
  Terminal.Gui/Core/TextFormatter.cs
  Terminal.Gui/Core/View.cs
  UnitTests/Views/ViewTests.cs
Labels: v1

#2756 Ensure unit test process dies; Back ported non-threaded `FakeMainLoop` from v2
  Terminal.Gui/ConsoleDrivers/FakeDriver/FakeMainLoop.cs
Labels: testing, v1

#2764 Fixes #2634 - Windows Terminal now clears correctly on exit
  Terminal.Gui/ConsoleDrivers/WindowsDriver.cs
Labels: v1
